//
// Copyright (c) 2025 ZettaScale Technology
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
// which is available at https://www.apache.org/licenses/LICENSE-2.0.
//
// SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
//
// Contributors:
//   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
//

package zenoh

// #include "zenoh.h"
// #include "zenoh_cgo.h"
// static const z_priority_t CGO_Z_PRIORITY_DEFAULT = Z_PRIORITY_DEFAULT;
// static const z_congestion_control_t CGO_Z_CONGESTION_CONTROL_DEFAULT = Z_CONGESTION_CONTROL_DEFAULT;
import "C"
import (
	"unsafe"
)

// The priority of zenoh messages.
type Priority int

const (
	PriorityRealTime        Priority = C.Z_PRIORITY_REAL_TIME        // Priority for ``RealTime`` messages.
	PriorityInteractiveHigh Priority = C.Z_PRIORITY_INTERACTIVE_HIGH // Highest priority for ``Interactive`` messages.
	PriorityInteractiveLow  Priority = C.Z_PRIORITY_INTERACTIVE_LOW  // Lowest priority for ``Interactive`` messages.
	PriorityDataHigh        Priority = C.Z_PRIORITY_DATA_HIGH        // Highest priority for ``Data`` messages.
	PriorityData            Priority = C.Z_PRIORITY_DATA             // Default priority for ``Data`` messages.
	PriorityDataLow         Priority = C.Z_PRIORITY_DATA_LOW         // Lowest priority for ``Data`` messages.
	PriorityBackground      Priority = C.Z_PRIORITY_BACKGROUND       // Priority for ``Background traffic`` messages.
	PriorityDefault         Priority = C.CGO_Z_PRIORITY_DEFAULT
)

// The congestion control policy to apply when routing zenoh messages.
type CongestionControl int

const (
	CongestionControlBlock   CongestionControl = C.Z_CONGESTION_CONTROL_BLOCK // Messages are not dropped in case of congestion.
	CongestionControlDrop    CongestionControl = C.Z_CONGESTION_CONTROL_DROP  // Messages are dropped in case of congestion.
	CongestionControlDefault CongestionControl = C.CGO_Z_CONGESTION_CONTROL_DEFAULT
)

// A Zenoh ID. In general, valid Zenoh IDs are LSB-first 128bit unsigned and non-zero integers.
type Id struct {
	id C.z_id_t
}

// Formats the `Id` into 16-digit hex string (LSB-first order).
func (id Id) String() string {
	var s C.z_owned_string_t
	C.z_id_to_string(&id.id, &s)
	loanedString := C.z_string_loan(&s)
	out := C.GoStringN(C.z_string_data(loanedString), C.int(C.z_string_len(loanedString)))
	C.zc_cgo_string_drop(&s)
	return out
}

// Return the byte sequence of the “Id“.
func (id Id) Bytes() []byte {
	return C.GoBytes(unsafe.Pointer(&id.id.id[0]), 16)
}

// A [Zenoh timestamp]. It consists of a time generated by a Hybrid Logical Clock (HLC) in NPT64 format and a unique zenoh identifier.
//
// [Zenoh timestamp]: https://zenoh.io/docs/manual/abstractions/#timestamp
type TimeStamp struct {
	timestamp C.z_timestamp_t
}

// Create uhlc timestamp from session id.
func (session *Session) NewTimestamp() TimeStamp {
	var ts TimeStamp
	C.z_timestamp_new(&ts.timestamp, C.z_session_loan(session.session))
	return ts
}

// Get the NTP64 time part of the timestamp.
func (timestamp TimeStamp) Time() uint64 {
	return uint64(C.z_timestamp_ntp64_time(&timestamp.timestamp))
}

// Get the [Id] associated with the timestamp.
func (timestamp TimeStamp) Id() Id {
	return Id{id: C.z_timestamp_id(&timestamp.timestamp)}
}

type qos struct {
	priority          Priority
	congestionControl CongestionControl
	isExpress         bool
}
