name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Zenoh-C dependencies
        run: |
          git clone https://github.com/eclipse-zenoh/zenoh-c.git
          cd zenoh-c
          mkdir build && cd build
          cmake .. -DZENOHC_BUILD_WITH_UNSTABLE_API=ON -DCMAKE_INSTALL_PREFIX="/tmp/local"
          cmake --build . --target install --config Release

      - name: Save dependencies artifact
        uses: actions/upload-artifact@v4
        with:
          name: zenoh-c-deps
          path: /tmp/local

  build:
    name: Build examples
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Download dependencies artifact
        uses: actions/download-artifact@v4
        with:
          name: zenoh-c-deps
          path: /tmp/local

      - name: Install dependencies
        run: make deps

      - name: Build all examples
        run: |
          export CGO_CFLAGS="-I/tmp/local/include"
          export CGO_LDFLAGS="-L/tmp/local/lib"
          export BIN_DIR="/tmp/local/bin"
          make

      - name: Save examples artifact
        uses: actions/upload-artifact@v4
        with:
          name: examples-deps
          path: /tmp/local

  test:
    name: Run tests
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Download dependencies artifact
        uses: actions/download-artifact@v4
        with:
          name: zenoh-c-deps
          path: /tmp/local

      - name: Run tests
        run: |
          export CGO_CFLAGS="-I/tmp/local/include"
          export CGO_LDFLAGS="-L/tmp/local/lib"
          export LD_LIBRARY_PATH="/tmp/local/lib"
          make test 

  test_examples:
    name: Run examples test 
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies artifact
        uses: actions/download-artifact@v4
        with:
          name: examples-deps
          path: /tmp/local

      - name: Run test_examples
        run: |
          export LD_LIBRARY_PATH="/tmp/local/lib"
          export BIN_DIR="/tmp/local/bin"
          chmod a+x ${BIN_DIR}/*
          make test_examples

  test_examples_quic:
    name: Run examples test with QUIC transport
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies artifact
        uses: actions/download-artifact@v4
        with:
          name: examples-deps
          path: /tmp/local

      - name: Run test_examples_quic
        run: |
          export LD_LIBRARY_PATH="/tmp/local/lib"
          export BIN_DIR="/tmp/local/bin"
          chmod a+x ${BIN_DIR}/*
          make test_examples_quic

  fmt:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check code format
        run: make fmt
